# Generated by Django 5.2.6 on 2025-10-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=150)),
                ('product_description', models.TextField()),
                ('product_category', models.CharField(max_length=100)),
                ('product_subcategory', models.CharField(max_length=100)),
                ('quantity_on_hand', models.IntegerField()),
                ('reorder_quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_rating', models.FloatField()),
            ],
            options={
                'ordering': ['product_category', 'product_name'],
            },
        ),
    ]
