# Generated by Django 5.2.7 on 2025-10-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
