# Generated by Django 5.2.7 on 2025-10-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_delete_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku_code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
