# Generated by Django 5.2.7 on 2025-11-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_voucher'),
        ('storefront', '0005_transactions_orderitem'),
    ]

    operations = [
    ]
