# Generated by Django 5.2.7 on 2025-11-09 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0006_merge_0004_voucher_0005_transactions_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'ordering': ['-transaction_datetime']},
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='transactions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='storefront.transactions'),
        ),
    ]
