# Generated by Django 5.2.8 on 2025-11-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_alter_product_sku_code'),
        ('storefront', '0006_shippingaddress'),
        ('storefront', '0007_alter_transactions_options_and_more'),
    ]

    operations = [
    ]
