# Generated by Django 5.2.8 on 2025-11-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0009_orderitem_price_at_purchase_transactions_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='total',
        ),
    ]
