# Generated by Django 5.2.8 on 2025-11-10 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0010_remove_transactions_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='transactions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='storefront.transactions'),
        ),
    ]
