# Generated by Django 5.2.7 on 2025-11-11 04:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0011_alter_orderitem_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='text_review',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='transactions',
            name='payment_method',
            field=models.CharField(choices=[('Wallet', 'Wallet'), ('Card', 'Card')], default='Card', max_length=20),
        ),
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('Payment Made', 'Payment Made'), ('Delivered to Warehouse', 'Delivered to Warehouse'), ('Delivery Completed', 'Delivery Completed')], default='Delivery Completed', max_length=50),
        ),
        migrations.AddField(
            model_name='transactions',
            name='voucher_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='voucher',
            name='issued_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voucher',
            name='used_count',
            field=models.IntegerField(default=0),
        ),
    ]
