# Generated by Django 5.2.7 on 2025-11-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0012_orderitem_rating_orderitem_text_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_sold',
            field=models.IntegerField(default=0),
        ),
    ]
