# Generated by Django 5.2.8 on 2025-11-13 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0014_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='text_review',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
