# Generated by Django 5.2.8 on 2025-11-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0017_cartitem_is_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('Payment Made', 'Payment Made'), ('Delivered to Warehouse', 'Delivered to Warehouse'), ('Delivery Completed', 'Delivery Completed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='Payment Made', max_length=50),
        ),
    ]
