# Generated by Django 5.2.8 on 2025-11-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0018_alter_transactions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('Payment Made', 'Payment Made'), ('Delivered to Warehouse', 'Delivered to Warehouse'), ('Delivery Completed', 'Delivery Completed'), ('Cancelled', 'Cancelled'), ('Request for Refund', 'Request for Refund'), ('Refund Approved', 'Refund Approved'), ('Refund Rejected', 'Refund Rejected')], default='Payment Made', max_length=50),
        ),
    ]
