# Generated by Django 5.2.8 on 2025-11-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0021_alter_transactions_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='shipping_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
