# Generated by Django 5.2.8 on 2025-11-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0022_alter_transactions_shipping_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='shipping_phone',
            field=models.IntegerField(default=91234567),
            preserve_default=False,
        ),
    ]
