# Generated by Django 5.2.6 on 2025-11-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0023_alter_shippingaddress_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
