# Generated by Django 5.2.6 on 2025-11-16 08:12

from django.db import migrations
from decimal import Decimal


def initialize_unit_costs(apps, schema_editor):
    """
    Initialize unit_cost as 30% off unit_price (70% of selling price)
    and total_cost as unit_cost * quantity_on_hand
    """
    Product = apps.get_model('storefront', 'Product')
    
    for product in Product.objects.all():
        # Calculate unit_cost as 70% of unit_price (30% discount)
        product.unit_cost = product.unit_price * Decimal('0.70')
        
        # Calculate total_cost based on current inventory
        product.total_cost = product.unit_cost * product.quantity_on_hand
        
        product.save()


def reverse_initialization(apps, schema_editor):
    """
    Reverse the initialization by setting costs back to 0
    """
    Product = apps.get_model('storefront', 'Product')
    Product.objects.all().update(unit_cost=0, total_cost=0)


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0024_add_unit_cost_fields'),
    ]

    operations = [
        migrations.RunPython(initialize_unit_costs, reverse_initialization),
    ]
