# Generated by Django 5.2.7 on 2025-10-23 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20)),
                ('employment_status', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Self-employed', 'Self-employed'), ('Unemployed', 'Unemployed'), ('Student', 'Student'), ('Retired', 'Retired'), ('Others', 'Others')], max_length=200)),
                ('occupation', models.CharField(max_length=200)),
                ('education', models.CharField(choices=[('No Formal Education', 'No Formal Education'), ('High School', 'High School'), ('Diploma', 'Diploma'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Doctorate', 'Doctorate'), ('Others', 'Others')])),
                ('household_size', models.IntegerField()),
                ('has_children', models.BooleanField(default=False)),
                ('monthly_income_sgd', models.DecimalField(decimal_places=11, max_digits=20)),
                ('preferred_category', models.CharField(max_length=100)),
                ('is_initial_password', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
