# Generated by Django 5.2.7 on 2025-10-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userprofile_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
