# Generated by Django 5.2.7 on 2025-10-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_userprofile_preferred_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_initial_password',
            field=models.BooleanField(default=False),
        ),
    ]
