# Generated by Django 5.2.7 on 2025-11-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_userprofile_is_initial_password'),
        ('storefront', '0007_alter_transactions_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vouchers',
            field=models.ManyToManyField(blank=True, to='storefront.voucher'),
        ),
    ]
