# Generated by Django 5.2.8 on 2025-11-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userprofile_wallet_balance'),
        ('authentication', '0005_userprofile_vouchers'),
    ]

    operations = [
    ]
