# Generated by Django 5.2.7 on 2025-11-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_merge_20251110_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(default=12345678),
        ),
    ]
