# Generated by Django 5.2.8 on 2025-11-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='monthly_income_sgd',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
