# Generated by Django 5.2.7 on 2025-11-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_userprofile_monthly_income_sgd'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_delivery_admin',
            field=models.BooleanField(default=False),
        ),
    ]
